Server release
ita-social-projects/Real-Time-Face-Mask-Detector-Server pull request #72
Opened 2021-03-15 07:38 UTC by ChyzhTolik

2021-03-15 08:41 UTC, ShostakOleh approved these changes

2021-03-17 19:05 UTC, OleksiiiSemko requested changes

2021-03-17 19:05 UTC, OleksiiiSemko commented on RealTimeFaceMaskDetector/Logger/Logger.h
> +//INITIALIZE_EASYLOGGINGPP
Let's delete this comment

2021-03-17 19:34 UTC, OleksiiiSemko approved these changes

2021-03-17 19:35 UTC, merged